# Menus
menu:
#  HOME: .
#  Archives: archives
  ★目录★: categories
  标签: tags
  关于我: 其它/关于我

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: images/logo_2.png
    profile:
        enabled: true # Whether to show profile bar
        avatar: css/images/avatar_gray_wolf_games.png
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: YangZheng
        author_title: web开发、UI设计、杂食
        location: 郑州
        follow: //shang.qq.com/wpa/qunwpa?idkey=f2d5272788c3f854c200b434112de63d96760f98db6b7f2f6135c67dd80b48cc
    highlight: github  # darcula github grayscale idea ascetic monokai
    sidebar: right # sidebar position, options: left, right or leave it empty
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: # path to favicon
    social_links: # http://fontawesome.com
        github: /   # default /
        qq: /     # themes/icarus/layout/common/profile.ejs
        weixin: images/logo_2.png
#        dribbble: /
#        rss: /
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - category
#    - recent_posts
#    - archive
#    - tag
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus:  # 谷歌邮箱 shortname:canaan_di 国内无法访问代理又比较麻烦 # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here
    facebook: # enter true to enable
    isso: # enter the domain name of your own comment isso server eg. comments.example.com
    changyan: # please fill in `appid` and `conf` to enable
        appid:
        conf:
    gitment:
        owner: #your github ID
        repo: #the repo to store comments
        #Register an OAuth application, and you will get a client ID and a client secret.
        client_id: #your client ID
        client_secret: #your client secret
    livere: MTAyMC8zNDgyOC8xMTM2NQ== # qq邮箱  # enter livere uid here
    valine: # Valine Comment System https://github.com/xCss/Valine
        on:  # enter true to enable
        appId:  # enter the leancloud application appId here
        appKey: # enter the leancloud application appKey here
        notify: # enter true to enable <Mail notifier> https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
        verify: # enter true to enable <Validation code>
        placeholder: Just Do It # enter the comment box placeholder


# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: 05945971757165c93bca4e5a2e545684 # enter Baidu Analytics hash key
    mathjax: false # options: true, false

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        Hexo: http://hexo.io
        hexo-theme-icarus: https://github.com/ppoffice/hexo-theme-icarus/wiki/Installation
